### ISSUE TITLE
links for eset files are broken

### ISSUE THREAD

**Issue by ghost** [neellab/simem#1]
Hi

I wanted to play around with this code and use the existing eset files however the links appear to be broken in the format_data.Rmd page

cheers
steve

**Comment by neellab** [comment]
Hi Steve,

Thanks for the heads-up. I'll update the documentation.

In the interim, there's a more up-to-date version of the documentation under the "gh-pages" branch. While the format_data.Rmd page still needs to be updated,  there is a link to the eset file in the two_class_analysis.Rmd file under the "gh-pages" branch:

https://neellab.github.io/simem/documentation/markdown/two_class_analysis.html

And here's the direct link to the eset:

https://www.dropbox.com/s/dp278iu9kle98fy/breast_screens_with_weights.eset?dl=1

Best,
Azin

**Comment by ghost** [comment]
Thanks Azin

In particular I am interested in looking at the achilles dataset and using this method to look at essentiality for some dozen genes or so...

cheers
steve

**Comment by neellab** [comment]
Hi Steve,

I was going to post the code I used to run the Achilles analyses in the manuscript, when I realized that I'd inadvertently broken the Achilles analysis functionality (the single time-point analysis) by doing some clean-up in the simem() function input parameters before the initial github upload. I'll be uploading a few minor updates to the code shortly, along with a link to the Achilles eset I used...

Cheers,
Azin

**Comment by neellab** [comment]
Hi Steve,

I've uploaded two tutorials using the Achilles data at https://neellab.github.io/simem as well as convenient download links to the screen data esets. The R code has also been tested and uploaded.

Azin

**Comment by ghost** [comment]
Thanks Azin!
